name: Publish TypeScript Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Use provided version
        id: use_version
        run: |
          VERSION="${{ inputs.version }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract release notes from CHANGELOG.md
        id: get_release_notes
        run: |
          TAG_NAME="v${{ inputs.version }}"
          RELEASE_NOTES=$(awk "/## $TAG_NAME/,/## /" CHANGELOG.md | sed '$d')
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Build the package
        run: yarn build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Store your npm token in GitHub Secrets
        run: |
          yarn version --new-version ${{ env.VERSION }} --no-git-tag-version
          yarn publish dist/ --new-version ${{ env.VERSION }} --no-git-tag-version

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" --notes "${{ env.release_notes }}"
